"""The B2C schema from PM spec section 28, as its own set of tables.

`app/models/recommended.py` declares the spec's table list verbatim — `users`, `phr_profiles`,
`check_sessions`, `bp_references` and the rest — and live endpoints (`profile.py`,
`check_sessions.py`, `device.py`, and the dual-write in `auth.py`) already query them. **None of
them existed.** There was no migration, so every one of those routes was a 500 waiting for its
first request, and the mobile app had already been switched to call them.

This creates them. It is deliberately a plain `create_table` set with no triggers and no
`synthetic` column, because that is what the models declare; see `docs/decisions.md` for why that
is a problem worth resolving rather than a shape to build on.

**Also renames one index.** `ix_session_context_session_id` was created by 0009 on a column later
renamed to `check_session_id`, so the name has been describing the wrong thing since. Same column,
same index, correct name — carried here because autogenerate proposes it on every run until it is
taken, and leaving standing drift in the tree is how a real change gets missed in the noise.

Revision ID: 0013_b2c_section_28
Revises: 0012_bp_reference
Create Date: 2026-08-13

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0013_b2c_section_28'
down_revision: str | None = '0012_bp_reference'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('devices',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('os_version', sa.String(), nullable=False),
    sa.Column('app_version', sa.String(), nullable=False),
    sa.Column('eligibility_status', sa.String(), nullable=False),
    sa.Column('camera_supported', sa.Boolean(), nullable=False),
    sa.Column('flash_supported', sa.Boolean(), nullable=False),
    sa.Column('accelerometer_supported', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_history',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('early_onset_boolean_optional', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_conditions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('condition_code', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('diagnosed_at_optional', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifestyle_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('physical_activity_level', sa.String(), nullable=True),
    sa.Column('smoking_status', sa.String(), nullable=True),
    sa.Column('nicotine_type', sa.String(), nullable=True),
    sa.Column('alcohol_frequency', sa.String(), nullable=True),
    sa.Column('usual_sleep_hours', sa.String(), nullable=True),
    sa.Column('usual_stress_level', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('medications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dose', sa.String(), nullable=True),
    sa.Column('dose_unit', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('last_changed_at', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phr_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex_assigned_at_birth', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('pregnancy_status', sa.String(), nullable=True),
    sa.Column('postpartum_date', sa.Date(), nullable=True),
    sa.Column('arrhythmia_status', sa.String(), nullable=True),
    sa.Column('hypertension_status', sa.String(), nullable=True),
    sa.Column('taking_bp_medication', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('check_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('bp_reference_id_optional', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bp_readings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id_optional', sa.Uuid(), nullable=True),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('pulse', sa.Integer(), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('source_manual_or_ocr', sa.String(), nullable=False),
    sa.Column('ocr_confidence_optional', sa.Float(), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('used_as_reference', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id_optional'], ['check_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insights',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('result_state', sa.String(), nullable=False),
    sa.Column('interpretation_code', sa.String(), nullable=True),
    sa.Column('priority_action_code', sa.String(), nullable=True),
    sa.Column('recommendation_codes_json', sa.String(), nullable=True),
    sa.Column('monitoring_plan_code', sa.String(), nullable=True),
    sa.Column('followup_code', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['check_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preconditions',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('rested_5_min', sa.Boolean(), nullable=False),
    sa.Column('recent_activity_30_min', sa.Boolean(), nullable=False),
    sa.Column('recent_caffeine_30_min', sa.Boolean(), nullable=False),
    sa.Column('recent_nicotine_30_min', sa.Boolean(), nullable=False),
    sa.Column('needs_restroom', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['check_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_measurements',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('ptt_ms', sa.Float(), nullable=True),
    sa.Column('heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('capture_duration', sa.Integer(), nullable=True),
    sa.Column('algorithm_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['check_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_context_b2c',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('sleep_less_than_usual', sa.Boolean(), nullable=False),
    sa.Column('stress_higher_than_usual', sa.Boolean(), nullable=False),
    sa.Column('feeling_unwell', sa.Boolean(), nullable=False),
    sa.Column('symptoms_json', sa.String(), nullable=True),
    sa.Column('medication_status_today', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['check_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_quality',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('quality_metrics_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['check_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_results',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('trend_state', sa.String(), nullable=False),
    sa.Column('comparison_window', sa.String(), nullable=True),
    sa.Column('baseline_reference', sa.String(), nullable=True),
    sa.Column('technical_details_json', sa.String(), nullable=True),
    sa.Column('model_or_rule_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['check_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bp_references',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bp_reading_id', sa.Uuid(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=False),
    sa.Column('deactivated_at_optional', sa.DateTime(), nullable=True),
    sa.Column('refresh_reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bp_reading_id'], ['bp_readings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_session_context_session_id'), table_name='session_context')
    op.create_index(op.f('ix_session_context_check_session_id'), 'session_context', ['check_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_context_check_session_id'), table_name='session_context')
    op.create_index(op.f('ix_session_context_session_id'), 'session_context', ['check_session_id'], unique=False)
    op.drop_table('bp_references')
    op.drop_table('trend_results')
    op.drop_table('signal_quality')
    op.drop_table('session_context_b2c')
    op.drop_table('sensor_measurements')
    op.drop_table('preconditions')
    op.drop_table('insights')
    op.drop_table('bp_readings')
    op.drop_table('check_sessions')
    op.drop_table('phr_profiles')
    op.drop_table('medications')
    op.drop_table('lifestyle_profiles')
    op.drop_table('health_conditions')
    op.drop_table('family_history')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
