"""``tera-docs`` — regenerate docs/api.md from the OpenAPI schema.

BUILD_SPEC 4.8 asks for "docs/api.md generated from OpenAPI". Generated rather than hand-written
so it cannot drift from the routes.
"""

from __future__ import annotations

from pathlib import Path

import typer

from app.main import app as fastapi_app

cli = typer.Typer(add_completion=False, help="Regenerate docs/api.md from OpenAPI.")

#: Written above the generated body so a reader knows the constraints before the endpoint table.
PREAMBLE = """<!-- GENERATED by `tera-docs`. Do not edit by hand; edit the route definitions. -->

# Tera API

Generated from the live OpenAPI schema.

## What this API will not do

- **No blood-pressure value is ever derived from the phone.** A `trend_estimate` carries a
  direction and a magnitude in units of the patient's own baseline standard deviation. There is
  no systolic field, no diastolic field and no conversion to mmHg. Only `cuff_reading` holds
  pressure values, and they come from a validated upper-arm cuff confirmed by a person.
- **No raw waveform is accepted.** The deepest granularity is one derived interval per beat, and
  the array carrying those intervals is length-bounded in configuration and by a database CHECK.
- **No clinical records are updated or deleted.** There are no PUT, PATCH or DELETE routes on any
  clinical resource. Corrections are new rows referencing the original.
- **No diagnosis, no medication advice, no clinical reassurance** in any response field.
- **Synthetic data is labelled.** Every response carrying a stored row exposes `synthetic`, and
  seeded rows also carry a `synthetic_notice`.

## Status codes on session ingest

| Code | Meaning |
|---|---|
| 201 | Session stored. `trend` is present only when a calibration was in force and the session was usable. |
| 400 | `Idempotency-Key` header missing, malformed, or not equal to `session_id`. |
| 409 | Duplicate `session_id`. The stored result is returned unchanged in the body. |
| 422 | Payload failed schema validation or the server-side plausibility gate. |
| 428 | `X-Session-Nonce` absent, expired, already used, or issued to a different caller. |
| 429 | Per-token or per-patient rate limit exceeded. `Retry-After` is set. |

A `201` with `trend: null` is a normal outcome, not an error: it means the session is on the
record but no estimate could responsibly be produced from it.

"""


@cli.command()
def main(
    output: Path = typer.Option(
        Path(__file__).resolve().parents[3] / "docs" / "api.md",
        "--output",
        help="Where to write the generated markdown.",
    ),
) -> None:
    """Write docs/api.md."""
    spec = fastapi_app.openapi()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_render(spec), encoding="utf-8")
    typer.echo(f"wrote {output}")


def _render(spec: dict) -> str:
    lines = [PREAMBLE, "## Endpoints", ""]

    for path, operations in sorted(spec["paths"].items()):
        for method, operation in sorted(operations.items()):
            lines.append(f"### `{method.upper()} {path}`")
            lines.append("")
            if summary := operation.get("summary"):
                lines.append(f"**{summary}**")
                lines.append("")
            if description := operation.get("description"):
                lines.append(description.strip())
                lines.append("")

            if params := operation.get("parameters"):
                lines.append("| Parameter | In | Required |")
                lines.append("|---|---|---|")
                for param in params:
                    required = "yes" if param.get("required") else "no"
                    lines.append(f"| `{param['name']}` | {param['in']} | {required} |")
                lines.append("")

            if body_ref := _request_body_schema(operation):
                lines.append(f"Request body: `{body_ref}`")
                lines.append("")

            lines.append("| Response | Description |")
            lines.append("|---|---|")
            for code, response in sorted(operation.get("responses", {}).items()):
                description = response.get("description", "").replace("\n", " ")
                lines.append(f"| `{code}` | {description} |")
            lines.append("")

    lines.append("## Schemas")
    lines.append("")
    for name, schema in sorted(spec.get("components", {}).get("schemas", {}).items()):
        lines.append(f"### `{name}`")
        lines.append("")
        if description := schema.get("description"):
            lines.append(description.strip())
            lines.append("")
        properties = schema.get("properties", {})
        if properties:
            required = set(schema.get("required", []))
            lines.append("| Field | Type | Required |")
            lines.append("|---|---|---|")
            for field, definition in properties.items():
                lines.append(
                    f"| `{field}` | {_type_of(definition)} | "
                    f"{'yes' if field in required else 'no'} |"
                )
            lines.append("")

    return "\n".join(lines) + "\n"


def _request_body_schema(operation: dict) -> str | None:
    content = operation.get("requestBody", {}).get("content", {})
    for media in content.values():
        ref = media.get("schema", {}).get("$ref")
        if ref:
            return ref.rsplit("/", 1)[-1]
    return None


def _type_of(definition: dict) -> str:
    if "$ref" in definition:
        return definition["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in definition:
        return " \\| ".join(_type_of(option) for option in definition["anyOf"])
    if "allOf" in definition:
        return " & ".join(_type_of(option) for option in definition["allOf"])
    if "const" in definition:
        return f"const `{definition['const']}`"
    if "enum" in definition:
        return "enum"
    type_name = definition.get("type", "object")
    if type_name == "array":
        return f"array of {_type_of(definition.get('items', {}))}"
    return type_name


def entrypoint() -> None:
    """Console-script entry point."""
    cli()


if __name__ == "__main__":  # pragma: no cover
    entrypoint()
